# Generated by Django 5.1.6 on 2025-03-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_todolist_user_alter_todolist_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('opened', 'Открыто'), ('closed', 'Закрыто')], default='opened', max_length=50),
        ),
    ]
